# Generated by Django 5.1.3 on 2024-12-14 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Car_App', '0003_brand_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='slug',
        ),
    ]
